### ISSUE TITLE
Crashes galore

### ISSUE THREAD

**Issue by justjoolz** [onflow/flow-emulator#189]
### Problem

Seeing a lot of uncaught crashes in the latest Version: v0.39.1 

Language server isn't catching some errors and they're causing trouble for the emulator...
"Expected casting" error was hidden way below verbose golang error logs and not caught by language server in vscode either

Other runtime errors also not being caught:

- calling verify in cadence with an invalid message/signature pair causes emulator to crash (but doesn't ask if you want to send crash report ie. just dumps verbose golang logs but does not fully crashes)....

**Comment by sideninja** [comment]
Thank you for reporting this to us! 

> Language server isn't catching some errors and they're causing trouble for the emulator...
"Expected casting" error was hidden way below verbose golang error logs and not caught by language server in vscode either

Can you let me know how we can reproduce this? 

> calling verify in cadence with an invalid message/signature pair causes emulator to crash (but doesn't ask if you want to send crash report ie. just dumps verbose golang logs but does not fully crashes)....

Interesting, will look into it and try catch those.

**Comment by sideninja** [comment]
Was this the casting error:
```
expected casting expression
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
	github.com/onflow/cadence@v0.24.2-0.20220725233315-443ea529bed1/runtime/errors/errors.go:139
github.com/onflow/cadence/runtime/parser.ParseTokenStream.func1()
	github.com/onflow/cadence@v0.24.2-0.20220725233315-443ea529bed1/runtime/parser/parser.go:113 +0x548
panic({0x101fc3240, 0x1400029d930})
	runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/parser.defineReferenceExpression.func1(0x14000234540, {0x2d, {0x0, 0x0}, {{0xba, 0x7, 0x15}, {0xba, 0x7, 0x15}}})
	github.com/onflow/cadence@v0.24.2-0.20220725233315-443ea529bed1/runtime/parser/expression.go:1304 +0x120
github.com/onflow/cadence/runtime/parser.applyExprNullDenotation(0x14000234540?, {0x2d, {0x0, 0x0}, {{0xba, 0x7, 0x15}, {0xba, 0x7, 0x15}}})
```

**Comment by justjoolz** [comment]
I forget exactly now but it was something like this, that :

```
    pub fun get(_ id: UInt64): MyStruct? {
        return &self.byID[id]
    }
   ```
   
the & shouldn't be there and language server misses it, trying to deploy crashes the emulator (with no error message)

**Comment by justjoolz** [comment]
```
❯ flow version
Version: v0.39.3

❯ flow project deploy

❗   Version warning: a new version of Flow CLI is available (v0.39.2).
   Read the installation guide for upgrade instructions: https://docs.onflow.org/flow-cli/install


❌ Crash detected! 

✔ No

Please help us improve the Flow CLI by opening an issue on https://github.com/onflow/flow-cli/issues, 
and pasting the output as well as a description of the actions you took that resulted in this crash.

internal error: expected casting expression
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
        github.com/onflow/cadence@v0.25.0/runtime/errors/errors.go:139
github.com/onflow/cadence/runtime/parser.ParseTokenStream.func1()
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:113 +0x548
panic({0x101fefa80, 0x1400045c0d0})
        runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/parser.defineReferenceExpression.func1(0x140007daa80, {0x2d, {0x0, 0x0}, {{0x4e4, 0x2c, 0xf}, {0x4e4, 0x2c, 0xf}}})
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1304 +0x120
github.com/onflow/cadence/runtime/parser.applyExprNullDenotation(0x140007daa80?, {0x2d, {0x0, 0x0}, {{0x4e4, 0x2c, 0xf}, {0x4e4, 0x2c, 0xf}}})
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1535 +0x14c
github.com/onflow/cadence/runtime/parser.parseExpression(0x140007daa80, 0x1010b712c?)
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1427 +0xec
github.com/onflow/cadence/runtime/parser.parseReturnStatement(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:219 +0xd4
github.com/onflow/cadence/runtime/parser.parseStatement(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:82 +0x90
github.com/onflow/cadence/runtime/parser.parseStatements(0x140007daa80, 0x1022707e8)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:44 +0x12c
github.com/onflow/cadence/runtime/parser.parseFunctionBlock(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:506 +0x310
github.com/onflow/cadence/runtime/parser.parseFunctionParameterListAndRest(0x140007daa80, 0x1)
        github.com/onflow/cadence@v0.25.0/runtime/parser/function.go:288 +0x230
github.com/onflow/cadence/runtime/parser.parseFunctionDeclaration(0x140007daa80, 0x90?, 0x4ae?, 0x2b?, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/function.go:222 +0x158
github.com/onflow/cadence/runtime/parser.parseMemberOrNestedDeclaration(0x140007daa80, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:1060 +0x46c
github.com/onflow/cadence/runtime/parser.parseMembersAndNestedDeclarations(0x140007daa80, 0x14)
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:1013 +0x9c
github.com/onflow/cadence/runtime/parser.parseCompositeOrInterfaceDeclaration(0x140007daa80, 0x100af7c28?, 0x1400083f198?, {0x140007c0d20, 0x5c})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:940 +0x468
github.com/onflow/cadence/runtime/parser.parseDeclaration(0x140007daa80, {0x140007c0d20, 0x5c})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:93 +0x4a4
github.com/onflow/cadence/runtime/parser.parseDeclarations(0x140007daa80, 0x1)
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:50 +0xb8
github.com/onflow/cadence/runtime/parser.ParseProgramFromTokenStream.func1(0x140007daa80?)
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:605 +0x20
github.com/onflow/cadence/runtime/parser.ParseTokenStream({0x0?, 0x0}, {0x102292840?, 0x14000589080}, 0x1022706b0)
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:146 +0x20c
github.com/onflow/cadence/runtime/parser.ParseProgramFromTokenStream({0x102292840, 0x14000589080}, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:601 +0x50
github.com/onflow/cadence/runtime/parser.ParseProgram({0x14000531c00?, 0x1017514a0?}, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:589 +0x74
github.com/onflow/flow-cli/pkg/flowkit/contracts.newContract(0x5, {0x140008d8ed0, 0x9}, {0x1400004af90, 0x17}, {0x14000531c00, 0xad0}, {0xf8, 0xd6, 0xe0, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/contracts/contracts.go:59 +0x5c
github.com/onflow/flow-cli/pkg/flowkit/contracts.(*Preprocessor).AddContractSource(0x1400083fa08, {0x140008d8ed0, 0x9}, {0x1400004af90, 0x17}, {0xf8, 0xd6, 0xe0, 0x58, 0x6b, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/contracts/preprocessor.go:60 +0xbc
github.com/onflow/flow-cli/pkg/flowkit/services.(*Project).Deploy(0x140003165d0, {0x1019a3d4d, 0x8}, 0x0)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/services/project.go:127 +0x1534
github.com/onflow/flow-cli/internal/project.deploy({0x0?, 0x0?, 0x0?}, {0x0?, 0x0?}, {{0x0, 0x0}, {0x10199f275, 0x4}, {0x0, ...}, ...}, ...)
        github.com/onflow/flow-cli/internal/project/deploy.go:53 +0x34
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x102dcf320?, {0x102e1f5f8, 0x0, 0x0})
        github.com/onflow/flow-cli/internal/command/command.go:128 +0x3a0
github.com/spf13/cobra.(*Command).execute(0x102dcf320, {0x1400011a1a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x140007ad400)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:82 +0x45c

[] []
map[device:map[arch:arm64 num_cpu:8] os:map[name:darwin] runtime:map[go_maxprocs:8 go_numcgocalls:3 go_numroutines:7 name:go version:go1.19]]
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/onflow/flow-cli/internal/command.initCrashReporting.func1(0x14000139440, 0x1400042aba0)
        github.com/onflow/flow-cli/internal/command/command.go:298 +0x1dc
github.com/getsentry/sentry-go.(*Client).processEvent(0x140008d51e0, 0x14000139440, 0x1400042aba0, {0x10227b580, 0x14000016000})
        github.com/getsentry/sentry-go@v0.13.0/client.go:548 +0x1a0
github.com/getsentry/sentry-go.(*Client).CaptureEvent(...)
        github.com/getsentry/sentry-go@v0.13.0/client.go:365
github.com/getsentry/sentry-go.(*Client).RecoverWithContext(0x1400007ad80?, {0x0?, 0x0}, {0x10215ebe0?, 0x1400042ecc0?}, 0x101764908?, {0x10227b580, 0x14000016000})
        github.com/getsentry/sentry-go@v0.13.0/client.go:416 +0x1e8
github.com/getsentry/sentry-go.(*Client).Recover(0x1400083da38?, {0x10215ebe0?, 0x1400042ecc0?}, 0x100af9604?, {0x10227b580?, 0x14000016000?})
        github.com/getsentry/sentry-go@v0.13.0/client.go:380 +0x80
github.com/getsentry/sentry-go.(*Hub).Recover(0x14000589080?, {0x10215ebe0?, 0x1400042ecc0?})
        github.com/getsentry/sentry-go@v0.13.0/hub.go:322 +0xc4
github.com/getsentry/sentry-go.Recover()
        github.com/getsentry/sentry-go@v0.13.0/sentry.go:65 +0x44
panic({0x10215ebe0, 0x1400042ecc0})
        runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/parser.ParseTokenStream.func1()
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:113 +0x5ac
panic({0x101fefa80, 0x1400045c0d0})
        runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/parser.defineReferenceExpression.func1(0x140007daa80, {0x2d, {0x0, 0x0}, {{0x4e4, 0x2c, 0xf}, {0x4e4, 0x2c, 0xf}}})
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1304 +0x120
github.com/onflow/cadence/runtime/parser.applyExprNullDenotation(0x140007daa80?, {0x2d, {0x0, 0x0}, {{0x4e4, 0x2c, 0xf}, {0x4e4, 0x2c, 0xf}}})
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1535 +0x14c
github.com/onflow/cadence/runtime/parser.parseExpression(0x140007daa80, 0x1010b712c?)
        github.com/onflow/cadence@v0.25.0/runtime/parser/expression.go:1427 +0xec
github.com/onflow/cadence/runtime/parser.parseReturnStatement(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:219 +0xd4
github.com/onflow/cadence/runtime/parser.parseStatement(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:82 +0x90
github.com/onflow/cadence/runtime/parser.parseStatements(0x140007daa80, 0x1022707e8)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:44 +0x12c
github.com/onflow/cadence/runtime/parser.parseFunctionBlock(0x140007daa80)
        github.com/onflow/cadence@v0.25.0/runtime/parser/statement.go:506 +0x310
github.com/onflow/cadence/runtime/parser.parseFunctionParameterListAndRest(0x140007daa80, 0x1)
        github.com/onflow/cadence@v0.25.0/runtime/parser/function.go:288 +0x230
github.com/onflow/cadence/runtime/parser.parseFunctionDeclaration(0x140007daa80, 0x90?, 0x4ae?, 0x2b?, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/function.go:222 +0x158
github.com/onflow/cadence/runtime/parser.parseMemberOrNestedDeclaration(0x140007daa80, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:1060 +0x46c
github.com/onflow/cadence/runtime/parser.parseMembersAndNestedDeclarations(0x140007daa80, 0x14)
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:1013 +0x9c
github.com/onflow/cadence/runtime/parser.parseCompositeOrInterfaceDeclaration(0x140007daa80, 0x100af7c28?, 0x1400083f198?, {0x140007c0d20, 0x5c})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:940 +0x468
github.com/onflow/cadence/runtime/parser.parseDeclaration(0x140007daa80, {0x140007c0d20, 0x5c})
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:93 +0x4a4
github.com/onflow/cadence/runtime/parser.parseDeclarations(0x140007daa80, 0x1)
        github.com/onflow/cadence@v0.25.0/runtime/parser/declaration.go:50 +0xb8
github.com/onflow/cadence/runtime/parser.ParseProgramFromTokenStream.func1(0x140007daa80?)
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:605 +0x20
github.com/onflow/cadence/runtime/parser.ParseTokenStream({0x0?, 0x0}, {0x102292840?, 0x14000589080}, 0x1022706b0)
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:146 +0x20c
github.com/onflow/cadence/runtime/parser.ParseProgramFromTokenStream({0x102292840, 0x14000589080}, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:601 +0x50
github.com/onflow/cadence/runtime/parser.ParseProgram({0x14000531c00?, 0x1017514a0?}, {0x0, 0x0})
        github.com/onflow/cadence@v0.25.0/runtime/parser/parser.go:589 +0x74
github.com/onflow/flow-cli/pkg/flowkit/contracts.newContract(0x5, {0x140008d8ed0, 0x9}, {0x1400004af90, 0x17}, {0x14000531c00, 0xad0}, {0xf8, 0xd6, 0xe0, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/contracts/contracts.go:59 +0x5c
github.com/onflow/flow-cli/pkg/flowkit/contracts.(*Preprocessor).AddContractSource(0x1400083fa08, {0x140008d8ed0, 0x9}, {0x1400004af90, 0x17}, {0xf8, 0xd6, 0xe0, 0x58, 0x6b, ...}, ...)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/contracts/preprocessor.go:60 +0xbc
github.com/onflow/flow-cli/pkg/flowkit/services.(*Project).Deploy(0x140003165d0, {0x1019a3d4d, 0x8}, 0x0)
        github.com/onflow/flow-cli/pkg/flowkit@v0.0.0-20220819152715-414ca9c1d221/services/project.go:127 +0x1534
github.com/onflow/flow-cli/internal/project.deploy({0x0?, 0x0?, 0x0?}, {0x0?, 0x0?}, {{0x0, 0x0}, {0x10199f275, 0x4}, {0x0, ...}, ...}, ...)
        github.com/onflow/flow-cli/internal/project/deploy.go:53 +0x34
github.com/onflow/flow-cli/internal/command.Command.AddToParent.func1(0x102dcf320?, {0x102e1f5f8, 0x0, 0x0})
        github.com/onflow/flow-cli/internal/command/command.go:128 +0x3a0
github.com/spf13/cobra.(*Command).execute(0x102dcf320, {0x1400011a1a0, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x140007ad400)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:82 +0x45c
```

**Comment by sideninja** [comment]
That's interesting. I will take a look into this as soon as I can, just pinging @turbolent meanwhile as well. Thank you for the report.

**Comment by justjoolz** [comment]
Similarly this also slips past the checks:
```
let resourceRef = &self.resources[uuid]? as &MyResource?
```

**Comment by turbolent** [comment]
Please do not report crashers publicly and follow https://www.onflow.org/flow-responsible-disclosure instead. Thank you!

**Comment by turbolent** [comment]
@justjoolz Thank you for reporting the issues, we are going to look into them. As a precaution, we've deleted the comments here.
