### ISSUE TITLE
Unlinking capability does not persist between transactions in emulator - v0.18.0

### ISSUE THREAD

**Issue by maeltr** [onflow/flow-emulator#46]
### Problem

When unlinking a capability in a first transaction, I am still able to access the reference from this capability in a second transaction. At the end of the first transaction, the capability appears as unlinked. 

This example is ran with the v0.18.0 of flow-cli.

### Steps to Reproduce

In a new folder, run `flow init`. 
Create two files:
- unlink.cdc: it unlink the receiver for the flow token vault. It does not panic, the capability is unlinked.
```
import FungibleToken from 0xee82856bf20e2aa6
import FlowToken from 0x0ae53cb6e3f42a79

transaction() {
    prepare(acct: AuthAccount) {
        acct.unlink(/public/flowTokenReceiver)

        if acct.getCapability<&{FungibleToken.Receiver}>(/public/flowTokenReceiver).borrow() != nil {
            panic("This should not be possible")
        }
    }
}
```
- check_unlink.cdc: it runs the same check as the previous transaction, but this time it panics.
```
import FungibleToken from 0xee82856bf20e2aa6
import FlowToken from 0x0ae53cb6e3f42a79

transaction() {
    prepare(acct: AuthAccount) {
        if acct.getCapability<&{FungibleToken.Receiver}>(/public/flowTokenReceiver).borrow() != nil {
            panic("This should not be possible")
        }
    }
}
```

Run the two transactions:
`flow transactions send unlink.cdc --signer emulator-account`
`flow transactions send check_unlink.cdc --signer emulator-account`

The second transaction panics but it should not.

### Acceptance Criteria

The capability should be unlinked in the second transaction, and this transaction should not panic.

**Comment by turbolent** [comment]
Tried to rule out that this an issue in Cadence itself by adding a test in onflow/cadence#849

**Comment by justjoolz** [comment]
I ran into this today too.

whilst testing edge cases where capabilities are unlinked.

```
transaction {
    var signer: AuthAccount
    var myPublicPath : PublicPath
  
    prepare(signer: AuthAccount) {
        self.signer = signer

        self.myPublicPath = /public/fusdReceiver
        let target = signer.getLinkTarget( self.myPublicPath)
        log(target)

        signer.unlink(self.myPublicPath)        
    }

    execute {

        self.signer.unlink(self.myPublicPath)
        
        let linkTarget = self.signer.getLinkTarget(self.myPublicPath)
        log( linkTarget )
       
    }
}
```
( I had everything in the prepare before but thought that might have been the problem so split it into prepare and execute  and made it verbose to try find out what's happening)

If I send this transaction on the emulator 

I get this (expected) output:
```
DEBU[0038] LOG [b843ff] /storage/fusdVault
DEBU[0038] LOG [b843ff] nil
```

but I get it every time I run it?.... and then eventually somewhat randomly it crashes the emulator with this error:

```panic: failed to update storage used by key publicfusdReceiver on account 179b6b1cb6755e31: storage used by key publicfusdReceiver on account 179b6b1cb6755e31 would be negative [recovered]
	panic: failed to update storage used by key publicfusdReceiver on account 179b6b1cb6755e31: storage used by key publicfusdReceiver on account 179b6b1cb6755e31 would be negative

goroutine 757 [running]:
github.com/onflow/flow-go/fvm.(*VirtualMachine).Run.func1(0x14000aa9ff0)
	github.com/onflow/flow-go@v0.15.3/fvm/fvm.go:59 +0x168
panic(0x100fa26a0, 0x14000704960)
	runtime/panic.go:965 +0x14c
github.com/onflow/cadence/runtime.(*runtimeStorage).writeCached(0x140004e8940, 0x140001cd100)
	github.com/onflow/cadence@v0.14.4/runtime/runtime_storage.go:393 +0xa8c
github.com/onflow/cadence/runtime.(*interpreterRuntime).ExecuteTransaction(0x14000553350, 0x140005b8480, 0x203, 0x240, 0x0, 0x0, 0x0, 0x1011c0598, 0x140003c05a0, 0x1011ab500, ...)
	github.com/onflow/cadence@v0.14.4/runtime/runtime.go:441 +0x4d8
github.com/onflow/flow-go/fvm.(*TransactionInvocator).Process(0x1400002cea0, 0x14000553410, 0x140001517a0, 0x14000b3a2c0, 0x14000155f60, 0x140006f3620, 0x0, 0x0)
	github.com/onflow/flow-go@v0.15.3/fvm/transaction.go:205 +0x62c
github.com/onflow/flow-go/fvm.(*TransactionProcedure).Run(0x14000b3a2c0, 0x14000553410, 0x1011b61d8, 0x101afe9f0, 0x10118e6d8, 0x14000553340, 0x0, 0x0, 0x0, 0x186a0, ...)
	github.com/onflow/flow-go@v0.15.3/fvm/transaction.go:59 +0xcc
github.com/onflow/flow-go/fvm.(*VirtualMachine).Run(0x14000553410, 0x1011b61d8, 0x101afe9f0, 0x10118e6d8, 0x14000553340, 0x0, 0x0, 0x0, 0x186a0, 0x3e80, ...)
	github.com/onflow/flow-go@v0.15.3/fvm/fvm.go:63 +0x150
github.com/onflow/flow-emulator.(*Blockchain).executeNextTransaction.func1(0x1011b39b8, 0x140006f3590, 0x14000000001, 0x14000474240, 0x14000972348, 0x100582498, 0x1)
	github.com/onflow/flow-emulator@v0.17.0/blockchain.go:818 +0x1e4
github.com/onflow/flow-emulator.(*pendingBlock).ExecuteNextTransaction(0x14000783c20, 0x14000972600, 0x14000553420, 0x7, 0x0)
	github.com/onflow/flow-emulator@v0.17.0/pendingBlock.go:152 +0x244
github.com/onflow/flow-emulator.(*Blockchain).executeNextTransaction(0x14000457d40, 0x1011b61d8, 0x101afe9f0, 0x10118e6d8, 0x14000553340, 0x0, 0x0, 0x0, 0x186a0, 0x3e80, ...)
	github.com/onflow/flow-emulator@v0.17.0/blockchain.go:808 +0x68
github.com/onflow/flow-emulator.(*Blockchain).executeBlock(0x14000457d40, 0x1000e002c, 0x14000972d68, 0x1005a5f68, 0x14000972d88, 0x100916000)
	github.com/onflow/flow-emulator@v0.17.0/blockchain.go:772 +0x198
github.com/onflow/flow-emulator.(*Blockchain).executeAndCommitBlock(0x14000457d40, 0x300000002, 0x14000972db8, 0x1000f4f54, 0x14000972de8, 0x1001067b0, 0x14000410d80)
	github.com/onflow/flow-emulator@v0.17.0/blockchain.go:901 +0x28
github.com/onflow/flow-emulator.(*Blockchain).ExecuteAndCommitBlock(0x14000457d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/onflow/flow-emulator@v0.17.0/blockchain.go:895 +0x78
github.com/onflow/flow-emulator/server/backend.(*Backend).CommitBlock(0x1400038dd20)
	github.com/onflow/flow-emulator@v0.17.0/server/backend/backend.go:524 +0x3c
github.com/onflow/flow-emulator/server/backend.(*Backend).SendTransaction(0x1400038dd20, 0x1011a9eb0, 0x1400090db60, 0x140005b8480, 0x203, 0x240, 0x0, 0x0, 0x0, 0x68f8469cd9df826d, ...)
	github.com/onflow/flow-emulator@v0.17.0/server/backend/backend.go:237 +0x60c
github.com/onflow/flow-emulator/server/backend.(*Adapter).SendTransaction(0x14000018738, 0x1011a9eb0, 0x1400090db60, 0x140005bbc80, 0xfce1fdb2085a0acf, 0x1f594329d687bdb1)
	github.com/onflow/flow-emulator@v0.17.0/server/backend/adapter.go:82 +0xbc
github.com/onflow/flow-go/access.(*Handler).SendTransaction(0x1400038dda0, 0x1011a9eb0, 0x1400090db60, 0x1400090db90, 0x1400038dda0, 0x3, 0x129191ed0)
	github.com/onflow/flow-go@v0.15.3/access/handler.go:174 +0x1a8
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_SendTransaction_Handler.func1(0x1011a9eb0, 0x1400090db60, 0x1010be200, 0x1400090db90, 0x26, 0x1400018e640, 0x0, 0x0)
	github.com/onflow/flow/protobuf/go/flow@v0.2.0/access/access.pb.go:2108 +0x7c
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x1011a9eb0, 0x1400090db60, 0x1010be200, 0x1400090db90, 0x140002b51a0, 0x140003f1800, 0x1010a8cc0, 0x1400090db60, 0x58, 0x1010df980)
	github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x8c
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_SendTransaction_Handler(0x10111cca0, 0x1400038dda0, 0x1011a9eb0, 0x1400090db60, 0x14000abb7a0, 0x1400019b4d0, 0x1011a9eb0, 0x1400090db60, 0x140005e1600, 0x29e)
	github.com/onflow/flow/protobuf/go/flow@v0.2.0/access/access.pb.go:2110 +0x12c
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400032d880, 0x1011b6358, 0x1400067b980, 0x140001cd200, 0x140003c3bc0, 0x101b11ac0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x1400032d880, 0x1011b6358, 0x1400067b980, 0x140001cd200, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400014eef0, 0x1400032d880, 0x1011b6358, 0x1400067b980, 0x140001cd200)
	google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

**Comment by janezpodhostnik** [comment]
Thank you @maeltr  and @justjoolz for the great bug report. I was able to find and fix the issue in https://github.com/onflow/flow-emulator/pull/47.
